### PR TITLE
Updates for transition to sburke781 ecowitt repo

### PR DESCRIPTION
**Pull request by sburke781**
Transition to hosting under my sburke781 ecowitt repository

### CODE REVIEW

**Comment by sburke781** [comment]
Sorry, I think I got this wrong, need to look at how to merge into my own copy of main...

**Comment by mircolino** [comment]
For HPM integration I think you also need to update and add back the repository.json file:

```
{
  "author": "Mirco Caramori",
  "gitHubUrl": "https://github.com/mircolino/ecowitt",
  "packages": [
    {
      "name": "Ecowitt WiFi Gateway",
      "category": "Integrations",
      "tags": [ "Monitoring", "Irrigation", "LAN", "Temperature & Humidity", "Water", "Weather" ],
      "location": "https://raw.githubusercontent.com/mircolino/ecowitt/master/packageManifest.json",
      "description": "Ecowitt Wifi Gateway driver for Hubitat Elevation"
    }
  ]
}
```

**Comment by mircolino** [comment]
Also, for templates to work properly you need to create sburke781/sburke781.github.io page repository and save there:

```
ecowitt/ecowitt.css
ecowitt/ecowitt.html
ecowitt/ecowitt.json
ecowitt/ecowitt.ttf
```

and of course update all the links accordingly.

**Comment by sburke781** [comment]
Thanks, yeah I noticed you must have removed it.  Not quite sure it's the best practice, but I decided to add the packages to my existing repo json file under my hubitat repository, which is already included in the HPM repositories listing.

Since then I've been having issues with HPM not recognising my copies of the drivers as the continuation of yours, so it may actually make more sense to setup a repo json like you mentioned in my copy of the ecowitt repo and then update the HPM repo link under your name, if that makes sense...

I hope you aren't put off by my changes to references to your name throughout the code.  Obviously the code links had to change for technical reasons, but I at least tried to keep references in the author notes.  I certainly can't claim any credit for the code, the changes were more to let people know who to talk to....

Thanks,
Simon

**Comment by sburke781** [comment]
I looked up the template / css file stuff and looked up the hosting you must have setup.  I changed them to raw links for now, but haven't tested if that will work....

**Comment by mircolino** [comment]
> I hope you aren't put off by my changes to references to your name throughout the code

Not at all. I actually really appreciate you doing this. Just perhaps in the author line add my github handle:

` * Author:     Simon Burke (Original author Mirco Caramori - github.com/mircolino)`

> I changed them to raw links for now, but haven't tested if that will work....

I remember last time I tried, raw links are no longer served with mime type text/html, hence the need for a github.io repo

**Comment by sburke781** [comment]
Ok, thanks, I'll update the Author reference and look at the github.io repo.

**Comment by sburke781** [comment]
BTW, I'm familiar enough with Git normally, but just on the whole forking, etc, do you know if the idea is for me to still run with the fork and use the re-release branch I setup as a new "main" or "master" branch, or should I have copied all the code and setup an ecowitt repo from scratch?  I'm happy to run with the fork for now, but if it's not the done thing I may transition it down the track.

**Comment by mircolino** [comment]
From an end user point of view I don't think it makes any difference.
I thought you created the re-release branch just to get things going again and then eventually merge that back to the main branch (and delete the re-release) when things are stable. This is what I'd do.

**Comment by sburke781** [comment]
When I tried to setup the Pull Request it kept wanting to merge it back into your main branch, as in not the one under my profile.  Not sure if that is what you intended, but I though you may have wanted to keep an archive of your own and I would host the code moving forward.  Not saying it has to be that way, just didn't want to mess with your codebase if that is not what you wanted...

**Comment by mircolino** [comment]
I didn't add you as a collaborator to my padus/ecowitt repo so there is no way you can change/update/modify that (unless you send me a PR and I approve it).
So you can safely merge re-release back to main and it will only change your ecowitt/main branch:

```
git checkout main
git pull origin main
git merge re-release
git push origin main
```

This is IMO the cleanest way forward and what I usually do: create a temporary branch to work on new features, and when I deem them stable, merge them back to main

**Comment by sburke781** [comment]
Ah, of course, not a PR, but a merge.  I do it all the time for work to merge main back into my dev branch, but always do a PR for merging back to main.  So easy to forget you can use the merge on it's own for completing a piece of work :-)

**Pull request closed without merging**
